### ISSUE TITLE
Create ETL script to move data from test trace case to test trace contacts

### ISSUE THREAD

**Issue by ljwoodley** [ctsit/tt_engine#1]
- [x] Read data from https://redcap-phone.ctsi.ufl.edu/prod/redcap_v9.3.5/Design/data_dictionary_codebook.php?pid=24

- [x] Copy case_name_*  fields from `redcap_event_name == case_investigation_arm_1 & is.na(redcap_repeat_instance)`

- [x] `filter(redcap_repeat_instrument == "covid19_case_contact_line_list")`

- [x] `filter(!is.na(contact_ll_firstname) | !is.na(contact_ll_lastname))`

- [x] `select(record_id, redcap_repeat_instance, contains("case_name"), contains("_ll_")) `

- [x] Upload filtered data to https://redcap-phone.ctsi.ufl.edu/prod/redcap_v9.3.5/Design/data_dictionary_codebook.php?pid=22

**Comment by pbchase** [comment]
instead of copying case_name_* from the case project, copy the case fields named here: https://redcap-phone.ctsi.ufl.edu/prod/redcap_v9.3.5/Design/online_designer.php?pid=22&page=case_and_contact_identifiers to be precise, they are case_id, case_name_first, case_name last, case_dob. case_id == record_id (where this record_id is from the case project)

Also, know that this job needs to be idempotent. You will need to read from the contact first selecting record_id, case_id, contact_instance_number. Then read the case data and anti-join with the existing contact data to prevent duplication or overwrite.

**Comment by pbchase** [comment]
You will need to add enough filters to the case project linelist data to determine if it is complete. otherwise you might copy a linelist entry that is not actionable. I think these fields must not be NA for the record to be copied:

```
contact_ll_firstname
contact_ll_lastname
contact_ll_datelastexposure
contact_ll_phone
```

**Comment by pbchase** [comment]
There is now a new field in case: contact_ll_trace. It indicates whether a contact needs to be traced. filter case LL data for contact_ll_trace == TRUE. 

Do not copy contact_ll_trace into contacts.

also, do not copy 

```
contact_ll_case_mask
contact_ll_contact_mask
```

**Comment by ljwoodley** [comment]
> You will need to add enough filters to the case project linelist data to determine if it is complete. otherwise you might copy a linelist entry that is not actionable. I think these fields must not be NA for the record to be copied:
> 
> ```
> contact_ll_firstname
> contact_ll_lastname
> contact_ll_datelastexposure
> contact_ll_phone
> ```

At least one of the fields must not be NA or all of these fields must not be NA?

**Comment by pbchase** [comment]
All of these fields must not be NA:

```
contact_ll_firstname
contact_ll_lastname
contact_ll_datelastexposure
contact_ll_phone
contact_ll_trace
```

note that I added `contact_ll_trace` to that list. :-)

**Comment by ljwoodley** [comment]
How is the `record_id` in tt contacts created. I'm trying to do the upload bu I get `ERROR: The record id field (record_id) is missing.` The only common fields between the two projects are below 
![Screen Shot 2020-05-07 at 2 38 31 PM](https://user-images.githubusercontent.com/35935416/81332173-a1973680-9070-11ea-8014-b1d9b1efa870.png)
I'm confused as to the best fields to match on as we can't use `record_id` and `redcap_event_name`? I thought `case_id` and `contact_instance_number` would work but there's still the matter of no `record_id`
@pbchase

**Comment by pbchase** [comment]
@ljwoodley , you ask 

> Are we creating the record_id in addition to setting redcap_event_name to "contact_tracing_arm_1" in the upload?

Yes, we will have to do that. Sorry, I forgot that record ID is not auto-created by the API if it is omitted. There is a switch for that in the API, `parameterforceAutoNumber=true`, but I don't see support in REDCapR. 

That said, if you have to read all of contacts first, you know the max record ID and and use that to create new, unique record IDs for the new records before writing them.
