### ISSUE TITLE
Remove case retests from results_requiring_manual_intervention

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#105]
Remove case _retests_ from `results_requiring_manual_intervention` in `write_lab_results_to_results_project.R`

These are harder because the UF-ID field is NA because we are loading the data into a followup event

![case_data_for_upload](https://user-images.githubusercontent.com/3356493/85579767-292d0a80-b609-11ea-9f37-7658625aacf1.png)

It might be wisest to get get `get_new_lab_results_for_cases` to return a list with the existing return value as the first element "$data" and the new element a vector, `$uf_ids` as the second element. `$uf_ids` would contain every UF_ID in cases that is getting a new lab result loaded.

All that said, we might be better served to include and exclude result records based on order_ids rather than UFIDs. Acc_numbers would be OK of order IDs are both available in the data frames we are passing.

**Comment by ljwoodley** [comment]
Addressed by issue #111
