### ISSUE TITLE
Write script process_cleared_data_in_cases.R

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#12]
Write script `process_cleared_data_in_cases.R`. this script should

1. Read cases data
2. Identify immediate clears
3. Identify people who should be withheld
4. Identify people who should be cleared for campus
5. Set case closed flags where appropriate

Items 2 and 4 might be the same operation

**Comment by pbchase** [comment]
To expand on the issue above, item 1 should read the Cases REDCap project much like in https://github.com/ctsit/tt_engine/blob/d670076911a637a6a6132467353f6135a0657bfd/functions.R#L1, but that function does not read enough columns. it would also need to read more data. 

@tlstoffs and I need to do more work to identify the rules for this issue. they will inform the columns to read.

**Comment by pbchase** [comment]
FYI active dev work is proceeding at https://github.com/ctsit/tt_engine/tree/feature/integrate_person_data

**Comment by pbchase** [comment]
Here's the clarity on items 2-4. it uses brand new variables @tlstoffs is adding to dev as I write this.

Assume the case data exists in a DF named `cases`

2. Identify immediate clears

```
case_trace == 0 & case_ufaffiliation_cleared_for_campus == 'Y'
```

3. Identify people who should be withheld

```
case_trace == 1 & (case_ufaffiliation_cleared_for_campus %in% c('Y', '') | is.na(case_ufaffiliation_cleared_for_campus))
```

4. Identify people who should be cleared for campus

```
case_trace == 1 & case_ufaffiliation_cleared_for_campus == 'Y'
```

**Comment by ljwoodley** [comment]
I'm confused by # 3. Below I've made the changes to what I think it should be. If this is incorrect what's your reasoning for those `case_ufaffi..` values?
`case_trace == 1 & (case_ufaffiliation_cleared_for_campus %in% c('N', 'I') | is.na(case_ufaffiliation_cleared_for_campus))`

@pbchase

**Comment by pbchase** [comment]
@ljwoodley, yea, do it your way. I'm a dummy.

**Comment by pbchase** [comment]
@ChemiKyle, @tlstoffs, this item is the new top priority at https://docs.google.com/document/d/16AAvTSawOJS6HvBPy43hVstPKy41xFuYT2a7bAlmkC8/edit# The # 2 priority will do the same for contacts.  

There might be ways to simplify the code if we rename some vars in cases and contacts to match the names in results.  Consider this entire plan:

## Copy cleared for campus flags from cases to results
1. Discuss with Kyle the plan to use his javascript code (https://github.com/pbchase/tt_engine/blob/restructure_docs/redcap_projects.md) to auto-adjust fields in 3 projects. The code has the field names `cleared_for_campus_timestamp` and `cleared_for_campus` embedded in it. Making these field names configurable would be hard. it would be simpler have a custom version of the code for each of the three projects. You might want to standardize the field names across all three projects to simplify both the javascript and R code that has to read and write these fields. That might break the local rules for field naming but it might be worth it.
1. Add a cleared_for_campus_date to field to cases
1. Apply Kyle’s Javascript hack to manage the updates to this field
1. Write a script (function?) to copy cleared for campus flag from case to results if the cleared_for_campus_date in source project is more recent than the same field on target project.
1. Run this script/function with relatively high frequency, say every 5 minutes.

**Comment by pbchase** [comment]
@ChemiKyle, @tlstoffs is going to make the field changes to embrace the names `cleared_for_campus_timestamp` and `cleared_for_campus` in all three projects.

**Comment by tlstoffs** [comment]
all 3 projects now have same field names: cleared_for_campus and cleared_for_campus_timestamp

**Comment by pbchase** [comment]
This issue has been superceded by issue #70
