### ISSUE TITLE
load_case_into_contacts.R in 0.21.0 does not write most contact fields

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#125]
`load_case_into_contacts.R` in release 0.21.0 does not write most contact fields. Take a look at https://github.com/ctsit/tt_engine/blob/197f81b4f415b65eccf965c3c7e0e61a78018936/load_case_into_contacts.R#L76

Columns `redcap_event_name, case_id, contact_instance_number` get written. the columns that should be includes in  `everything()` are not. This problem started on 7/15 when 0.21.0 was released and deployed. See https://redcap-phone.ctsi.ufl.edu/prod/redcap_v10.0.1/DataExport/index.php?pid=26&report_id=105 to understand why we think this.  

@tlstoffs helped research this.

**Comment by ljwoodley** [comment]
This issue comes from `case_first_name` and `case_last_name` being NA? That's a strange reason. We also did not get any upload errors from the script so the data is being written but dropped in REDCAp somehow...

**Comment by tlstoffs** [comment]
Looking at the logging for one of the records that is missing the Case information, case_name_last or case_name_first was never uploaded into this record: https://redcap-phone.ctsi.ufl.edu/prod/redcap_v10.0.1/Logging/index.php?pid=26&logtype=&dag=&usr=&beginTime=&endTime=&record=650

**Comment by ljwoodley** [comment]
Hmm we may have to do a backfill for these records

**Comment by ljwoodley** [comment]
Addressed by PR #126
