### ISSUE TITLE
Create process_screen_fails.R

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#127]
Create a new ETL Rscript to handle screen fail dispositions. Name it `process_screen_fails.R`.  This script will read the screening project, subset the data by values in the `failed_screen_disposition` field and a time field and take some action. The actions could be to write a list of UFIDs to a file in SFTP space or update a field in the screening REDCap project. This script will run daily, processing only the previous day's data. 

In its first iteration, the project should send people for rescreening. That process will look like this:

1. Read the screen data from https://redcap-phone.ctsi.ufl.edu/prod/redcap_v10.0.1/index.php?pid=34
1. `filter(failed_screen_disposition == 2)`
1. filter for `interview_date` == yesterday.
1. select record_id
1. rename record_id to screen_id
1. write output to a csv with a basename of 'expire_screening_'. Append the usual time-stamped extension.
1. upload the CSV to 'data_out/redcap/' using a system call to `put_file.sh`
1. log the upload activity and job success metrics in an email to you and me.

Make sure to include plenty of error checking to assure that we know when the job fails.

These criteria are not exactly those being used to send the automated email alerts from REDCap. There is a risk the criteria described here would let a screen fail fall through the cracks. This would happen if `interview_date`, but `failed_screen_disposition` is not. Please run some data checks to see if we have records wherein `interview_date` is set, but `failed_screen_disposition` is not. We might need to revise the plan if any such records exist. We might need to make the `failed_screen_disposition` field required in the REDCap project.  I'm looping in @tlstoffs to get her opinion. This report only shows one such record: https://redcap-phone.ctsi.ufl.edu/prod/redcap_v10.0.1/DataExport/index.php?pid=34&report_id=154

Note: future additions to this report will address most if not all the values of `failed_screen_disposition`

**Comment by tlstoffs** [comment]
The problem with making the failed_screen_disposition field be required is that if they have not reached the person, they cannot set this field. Also, one of the answer options is that they couldn't reach the person after numerous attempts, so if I add branching logic to the failed_screen_disposition field where they have to say they reached the person to show this field, the field will never be set if they never reached the person. So I'd leave that field as is. 

<img width="792" alt="Screen Shot 2020-08-05 at 1 56 26 PM" src="https://user-images.githubusercontent.com/21062119/89447143-84cbd700-d723-11ea-9973-43e4c8887190.png">

**Comment by pbchase** [comment]
note, we will send the record_id under the name screen_id

**Comment by ljwoodley** [comment]
Addressed by PR #128
