### ISSUE TITLE
Backfill person_type and uf_affiliate in cases and contacts

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#130]
Backfill `person_type` and `uf_affiliate` in Cases and Contacts where those values are NA. 

The concepts of UF Affiliate and person type are temporal. Ones affiliation with UF changes over time. Yet each Case and Contact record describes a single point in time. As such, the Case and Contact records should reflect the person_type and uf_affiliation value at the case or contact is reported. As person_type was added later, it is NA on a lot of older records. uf_affiliation doesn't have a lot of missing values, but it too does not always reflect the correct person type.

To address this problem, write a new ETL script the runs daily at about 5:30 p.m. that 

1. finds missing `person_type` values in the Case and Contacts and fills them with the current values recorded in the Results project. 
1. Recomputes `uf_affiliation` based on person_type so that `uf_affiliation = 1` if `case_person_type %in% c("EMPLOYEE", "STUDENT", "BOTH", "OTHER")` and `uf_affiliation = 0`, otherwise.

This script could determine the UFIDs of interest from Cases and Contacts and use those values to create filter logic for the read of the Results project. 

This daily backfill operation will allow us to determine person_type directly from the Case or Contact data. It will also allow us to use `uf_affiliation == 1` as a proxy for `case_person_type %in% c("EMPLOYEE", "STUDENT", "BOTH", "OTHER")`. We will use this feature to streamline reports in an other issue. 

Note: this issues was born as https://github.com/ctsit/tt_reporting/issues/68 then moved here.

**Comment by ljwoodley** [comment]
Addressed by PR #133
