### ISSUE TITLE
get_new_lab_results_for_cases does not set housing fields

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#137]
`get_new_lab_results_for_cases` does not set housing fields. `get_new_lab_results_for_cases` is called by `write_lab_results_to_results_project.R` which uses its output to create case records. See https://github.com/ctsit/tt_engine/blob/de604995f5399feb964b52bb0e360f7cec8cd66c/R/data_creating.R#L157

The fields that need to be added are `uf_housing`, `data_source`, and `infection_area`.

**Comment by ljwoodley** [comment]
Addressed by PR #139
