### ISSUE TITLE
load_roomates_into_linelist.R overwrites existing linelist entries

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#140]
`load_roomates_into_linelist.R` overwrites existing linelist entries. This line needs to add an offset = the highest existing `redcap_repeat_instance` number on the Case record:

https://github.com/ctsit/tt_engine/blob/366abe085381f4403f47f87566f6562863d6e1b6/load_roomates_into_linelist.R#L100

**Comment by ljwoodley** [comment]
would redcap_repeat_instance be set automatically if that line is removed? @pbchase

**Comment by ljwoodley** [comment]
Addressed by PR #141
