### ISSUE TITLE
Housing data read changes

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#143]
Make this REDCap change in the Housing project:

1. add `checkin_date` column, a YYYY-MM-DD date column.
1. add an `expired_record` column, a Y/N column.

Revise `process_housing_data.R` to

- [x] use a `record_id` that is a hash of ufid, dob and first name.

- [x] read a new `checkin_date` column in place of `checkin_or_anticipated_date`
- [x] When loading the new data file, also set `expired_record = 0` for every record in the file.
- [x] Do anti-join of REDCap Housing data with file of housing data. 
- [x] Set `expired_record = 1` for every record in the anti-join.
- [x] In Results, set uf_housing = n, data_source = NA and infection_area = NA for every record in the anti-join.

Once the code is revised and ready for deployment do these steps:

1. Erase all data from the REDCap Housing data project.
2. Remove `checkin_or_anticipated_date` column from the REDCap Housing data project.
3. Run the revised `process_housing_data.R` to reload the new data into the Housing project.

@tlstoffs, can you make the initial REDCap changes and assist with the final changes after the code changes are made?

**Comment by ljwoodley** [comment]
addressed by issue #146
