### ISSUE TITLE
Revise REDCap projects and scripts to consume JAX cohort data

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#145]
We need to consume 1 or 2 new columns of that will identify the people in the Jacksonville cohort. 
The columns will be boolean data added to the person data. James Martinez is creating a test file that will precisely show the file we will need to consume. 

To implement the change, follow these steps:

1. Read the test dataset to determine the new column names. We will use a lowercased version of the name James provides. We will convert the boolean data to 1/0 to be compatible with a REDCAp Yes/No field.
1. Add the new fields in the production Results REDCap project on the 'UF Identifiers and Determination' form. Make them Yes/No fields.
1. Copy the new fields in the production Screens REDCap project.
1. Revise `load_person_data_into_results.R` to read the new fields, mutate their values to 1/0 and write them to Results along with the other person data.
1. Revise ~~`process_screen_fails.R`~~ `load_screen_into_follow_up.R` to select these fields after the join of person data to screen data and write the new values to the screen project.

After code review perform these steps to deploy the new software:

1. Arrange a cut-over time with James Martinez. 
1. Stop the cron jobs for these two scripts before the new data drops. 
1. Deploy the release.
1. Run the revised jobs manually. Verify the new data wrote.
1. Reenable the cron jobs for each of the revised scripts. 

With that done, do this to use the new data:

1. Revise the dashboards in the Screens project to subset data into JAX or not JAX based on the new fields instead of the domain part of the email address.
1. Inform Dr. Berry and Liz of the change and the potential effect on their dashboard.

@tlstoffs, we will need your assistance at the beginning and end of this issue.

**Comment by ljwoodley** [comment]
> where can I find the new column names for "Read the test dataset to determine the new column names. We will use a lowercased version of the name James provides. We will convert the boolean data to 1/0 to be compatible with a REDCAp Yes/No field."

Here are the names and definitions for the new fields:

1. rtcx_flag (Jacksonville – UF Employees)
2. rtch_flag (Jacksonville Controlled Test)               
3. rtcj_flag (Clinical Students Non Gville. This was included because these were cohorts in various locations including Jacksonville as well as Hialeah, Lake Nona, and Naples)

@tlstoffs

**Comment by tlstoffs** [comment]
your guess is as good as mine. i haven't seen the dataset....

**Comment by ljwoodley** [comment]
I'm saying those are the new field names. I just downloaded the dataset.

**Comment by tlstoffs** [comment]
So I am adding
rtcx_flag (Jacksonville – UF Employees)
rtch_flag (Jacksonville Controlled Test)
rtcj_flag (Clinical Students Non Gville.) 

as yes/no fields?

**Comment by ljwoodley** [comment]
Yep

**Comment by tlstoffs** [comment]
Fields have been added to Results (production) on the UF Identifiers and Determination form. They are readonly.

**Comment by ljwoodley** [comment]
thanks.

**Comment by ljwoodley** [comment]
@pbchase @tls these fields should also be added to screen project based on step 5 right?

`
5. Revise load_screen_into_follow_up.R to select these fields after the join of person data to screen data and write the new values to the screen project.
`

**Comment by tlstoffs** [comment]
I believe so, so I added them to the Screening project as well

**Comment by ChemiKyle** [comment]
@pbchase @tlstoffs I merged @ljwoodley's PR #157 for this, is everything in working order?

**Comment by pbchase** [comment]
I think we're fine.  I'm closing this.
