### ISSUE TITLE
Create a new ETL, request_clinical_results_for_uf_affiliates.R

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#152]
Create a new ETL, `request_clinical_results_for_uf_affiliates.R`, that reads Contacts to get a list of UFIDs of Contacts filtered for “Get Clinical Results” = 1 and `contact_tracing_date` is within the past 3 weeks. Write this result as a file for the EPIC team so they can include these Clinical lab results into the current ‘STP Lab Results’ file feed. 

Note: this Issue is dependent on @tlstoffs creating the new field for “Get Clinical Results” field. 

This ETL should have the normal features of any modern ETL in the tt_engine product including:

1. read config with .env
1. error handling during redcap data read.
1. email alerting to read errors
1. email of successful of runs.

Note that this ETL will soon consume other redcap data sources to identify UFIDs that should be added to the output file. Feel free to plan for this, but we will start with this one feed of Contacts data.

**Comment by tlstoffs** [comment]
Field added to get clinical results (checkbox field type)

[contact_clinical_results(1)] = '1'

**Comment by pbchase** [comment]
@ljwoodley, I just finished the first version of the spec that defines this file. Check your inbox.  Here are the most relevant excerpts:

> The REDCap team will provide a per-person start date for each UFID to limit the query to the appropriate time window. The start date will likely be a contact interview date or SHCC clinical visit date, but will ultimately be determined by Contact Tracing and SHCC workflows. The REDCap team will only include UFIDs are still relevant given the start date. Typically this would be for about 3 weeks. After that, a given UFID will be dropped from the list of UFIDs in the request for clinical COVID-19 results.
 
> This is a typical series of events in the workflow:
> At 8 p.m., REDCap runs a job to send a file, _UFID input file to the Epic team_, via SFTP.

That job that runs at 8 p.m. is this new ETL, `request_clinical_results_for_uf_affiliates.R`

> These are the paths at sftp.ahc.ufl.edu for the files referenced above: 
> UFID input file Epic team - data_out/redcap/redcap_to_idr_clinical_result_request_

> The file UFID input file Epic team - data_out/redcap/redcap_to_idr_clinical_result_request_ will have these columns:
> 
> uf_id (All 8 digits with leading zeros)
> first_name (As it appears in the UF Person Hub data)
> middle_name (As it appears in the UF Person Hub data)
> last_name (As it appears in the UF Person Hub data)
> date_of_birth (yyyy-mm-dd)
> start_date (yyyy-mm-dd)

**Comment by ljwoodley** [comment]
Does `start_date` in r`edcap/redcap_to_idr_clinical_result_request` refer to the `contact_tracing_date`? @pbchase

**Comment by ljwoodley** [comment]
Addressed by PR #154
