### ISSUE TITLE
refactor load_person_data_into_results.R to accept dev_mode as an arg

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#23]
Refactor `load_person_data_into_results.R` to use a command line argument to activate `get_person_data(dev_mode = TRUE)`.

Don't forget a README update.

**Comment by ChemiKyle** [comment]
cli args will be of the format var_name=var_value

**Comment by pbchase** [comment]
`dev_mode` might be a crummy parameter name.  feel free to change it to anything you like.

**Comment by ChemiKyle** [comment]
I'm leaving it for consistency now.

**Comment by pbchase** [comment]
yea, that's wise at this time.

**Comment by ChemiKyle** [comment]
Addressed by #26

Usability when calling from docker unconfirmed as `openxlsx` will not install during `docker build`
