### ISSUE TITLE
create a new script to send cleared data to person hub

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#27]
Create a _new script_ to send cleared_for_campus data to person hub. name the script `send_cleared_status_to_person_hub.R`

Read `record_id` and `cleared_for*` fields from redcap results project. filter for rows with NA instance number and NA repeat form. Rename `record_id` to `ufid`. use `write_csv` to write that to a file.  Name the output file according to this pattern 
`redcap_to_wh_cleared_for_campus_20200520170101.csv`. use a system call to `put_file.sh` to write that file to the target directory `data_out/redcap/`. `unlink` the local file as soon as it is uploaded. 

look for put_file.sh example in `create_a_small_person_dataset.R`

**Comment by pbchase** [comment]
Exclude rows for which `is.na(cleared_for_campus)`

**Comment by pbchase** [comment]
Can you adjust options on write_csv to wrap every column in quotes? Person hub peeps want that.

**Comment by ChemiKyle** [comment]
I was just looking at their data to make sure my formatting was right.
Do they want microsecond "precision" on time?

**Comment by pbchase** [comment]
they are happy with integer seconds

**Comment by ChemiKyle** [comment]
All cells are wrapped in quotes, do headers need to be in `ALL_CAPS`?

**Comment by pbchase** [comment]
closed by PR #29
