### ISSUE TITLE
address non-zero padded UFIDs

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#39]
We need to decide what to do about the non-zero padded UFIDs.  we padded them to make matches, found matches, then wrote the result data without the padding. This has made orphaned result data in the Results project.  We need to choose a course. I think we can choose one of thes two options:

1. pad UFID, match, revise UFID and write
1. don't pad at all.

We went half way down the first option and made a small mess.

**Comment by ChemiKyle** [comment]
There is a stringr function to [pad to a specified width](https://www.rdocumentation.org/packages/stringr/versions/1.4.0/topics/str_pad). I imagine the real question is with the acceptability of modifying `uf_id_from_order_q` and writing that to redcap, since it would mean different data in redcap than what we were given; I thought we were going to leave it to the data providers to handle the dropped padding?

**Comment by pbchase** [comment]
we were going to do that Kyle, but the data providers have not done that as far as I can tell. We might be wiser to roll with the punches, transform the data to valid and load it.

**Comment by pbchase** [comment]
whatever we do, we have to be 100% self-consistent.

**Comment by ljwoodley** [comment]
Hmm maybe sticking with the padding is the best route if the data providers are unreliable. Plus they may not always be consistent with the padding if it's done manually. I don't see any downsides to use doing the padding.

**Comment by pbchase** [comment]
Make these changes:

1. Zero-pad left every UF_ID to get an 8-digit string.
1. make sure `align_lab_results_to_person_data` returns the _revised_ UFID that it matched.
1. revise `write_lab_results_to_results_project.R` to use the UFID from `align_lab_results_to_person_data` as the authoritative UFID.

`write_lab_results_to_results_project.R` uses `align_lab_results_to_person_data`output at lines 41, 46, and 51.  It uses it in a different context at line 105.

**Comment by pbchase** [comment]
addressed by PR #42
