### ISSUE TITLE
Create an ETL job to load screen data into a new project

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#56]
Create an ETL job to load screen data into a new project.  Use the goodies at https://github.com/ctsit/tt_engine/tree/add_get_screen_data to make a new ETL script that joins a subset of screen data with person data and loads it into the dev REDCap project, https://redcap-phone.ctsi.ufl.edu/prod/redcap_v9.3.5/DataEntry/index.php?pid=33. 

Name the new rscript `load_screen_fails_and_caregivers_into_screen_follow_up.R`.  Use https://github.com/ctsit/tt_engine/blob/add_get_screen_data/export_screen_fails_and_caregivers.R for the bulk of the new rscript. You can drop the mutate statement in https://github.com/ctsit/tt_engine/blob/9b36d53f2b3415b752dea8e8c74586e0ea46160c/export_screen_fails_and_caregivers.R#L22. In that same line rename screen_id to record_id. 

Add the code that transforms symptom data into checkbox fields at https://github.com/ctsit/tt_engine/blob/9b36d53f2b3415b752dea8e8c74586e0ea46160c/inspect_screen_data.Rmd#L49 and line 59 of the same file.

You will need to extend the existing environment file to support a 4th redcap project called "screen_follow_up". Add appropriate env vars to this project in that file

Write the resulting data frame to https://redcap-phone.ctsi.ufl.edu/prod/redcap_v9.3.5/DataEntry/index.php?pid=33

**Comment by ChemiKyle** [comment]
Undoing the reintroduction of `openxlsx` is outside of the scope of my PR but will need to be addressed and remedied for dockerization; my payload script does not need it.

**Comment by ChemiKyle** [comment]
Addressed by #57
