### ISSUE TITLE
get_positive_cases_from_new_lab_results

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#68]
Note: This issue is the "Move positives to cases" and "Move negative retests to cases" at (https://docs.google.com/document/d/16AAvTSawOJS6HvBPy43hVstPKy41xFuYT2a7bAlmkC8/edit#).

Write a function,`get_positive_cases_from_new_lab_results`, to create a dataframe suitable for loading as new data into Cases. This function will be called within `write_lab_results_to_results_project.R`. For input it should accept the `new_lab_results` data frame. It should also accept `all_rows_in_redcap_results` to get the required identifiers from the primary form of that project. for creating It should also accept a new data frame of the data from the Cases project, call it `case_data`.  

The function should filter `new_lab_results` for only positive results. It should then

1. Join `new_lab_results` with `case_data` by UF_ID to identify retests. It should create a record for adding the retest data to the existing case record. The retest record should include these variables:
```
record_id
case_emp_ufid = uf_id
redcap_event_name (followup_1_arm_1, followup_2_arm_1, ... followup_NN_arm_1)
case_lab_collect_date
case_lab_report_date
case_lab_result
```
2. Anti_join `new_lab_results` with `case_data` by UF_ID to identify new cases. Filter `all_rows_in_redcap_results` for `is.na(redcap_repeat_instance)`, then inner join that to the output of the aforementioned anti_join to get the person data needed to create a case record. Use the output of these joins to create a record for adding the new case record.

The new case record should include these variables:
```
record_id
redcap_event_name ('case_investigation_arm_1')
case_lab_collect_date (formatted as "MM-DD-YYYY HH:MM")
case_lab_report_date (formatted as "MM-DD-YYYY HH:MM")
case_lab_result (
case_report_datetime (now() formatted as "MM-DD-YYYY HH:MM")

case_name_first = first_name
case_name_middle_1 = middle_name
case_name_last = last_name
gatorlink_id = gatorlink
case_phone = phone_number
case_email = email
case_dob = date_of_birth
case_age = age
case_sex = sex
case_race = race
```

You will need to recode these data for these radio button fields:

**case_sex**
- 1	Male
- 2	Female
- 88	Other
- 999	Unknown

**case_race**
- 1	African-American/Black
- 2	Asian/Pacific Islander
- 3	Native American
- 4	White
- 55	Other
- 88	Unknown
- 99	Preferred not to answer
 
3. Row bind the results of 1 and 2

4. Write the result of step 3 into Cases of nrow of step 3 > 0

5. Report the count of records written to cases in the email body.

A REDCap Email Alert to send an email or SMS to the DI team with a URL to the new record. @tlstoffs will make this part.

**Comment by senrabc** [comment]
And this too please:

From Notes:
6. Move negative retests to cases (Note: positive retests are handled in issue #68, https://github.com/ctsit/tt_engine/issues/68)

**Comment by pbchase** [comment]
That feature is already in the design, @senrabc

**Comment by pbchase** [comment]
The function `get_positive_cases_from_new_lab_results` needs to return three types of records:

1. New positives
1. Positive retests for existing cases
1. Negative retests for existing cases

Consider renaming it to `get_new_lab_results_for_cases` to reflect the handling of negative test results as well.
