### ISSUE TITLE
Add rejection reason as a data element to the rejection file

### ISSUE THREAD

**Issue by ljwoodley** [ctsit/tt_engine#74]
![Screen Shot 2020-06-12 at 5 26 32 PM](https://user-images.githubusercontent.com/35935416/84547579-dcc10100-acd1-11ea-99a7-9f90246362c3.png)

**Comment by pbchase** [comment]
Here's a more specific request from Patty's team:

> From: "Blanchard, Michael D." <blanmd@XXXXXXXX>
> Date: Friday, June 19, 2020 at 2:08 PM
> To: Philip Chase <pbc@XXXXXX>
> Cc: "DeGraff,Patty E." <maynap@XXXXXXX>
> Subject: RE: Rejected REDCAP Records Discussion - Couple of Requests
> 
> Hi Philip,
> Was wondering if you’d make a couple of tweaks to the inbound result processing to redcap.  
>  
> Request 1:
> It would be helpful if we could have a reject reason.  If my analysis of the rejected output is correct there are 3 reject reasons…
> 1)	No UF ID in results file.
> 2)	UF ID not found in redcap.
> 3)	UF ID found but name discrepancy prevents posting.
>  
> It would save some time on the researching end if the above and any other reject reasons that make sense to you were added as a column at the right in the “redcap_to_epic_rejected_lab_data_...” csv files.  
>  
> Request 2:
> For scenario 3 above, could you add an additional name comparison to your algorithm before rejecting the results on a name discrepancy using the following for the comparison?
>  
> -	Strip the hyphens from the name in redcap and compare it to what Patty sends in the results file.  
>  
> We have a result record that is failing as best I can tell because the patient has a hyphen in both the last name and the first name.  The DOB enhancement from earlier this week allowed the rest of the name discrepancies to flow through but the current algorithm seems to want an exact match on either first or last name…which can be met due to special characters restrictions in Epic.  I suspect we may see other instances of this when we hit the student population so thought it might eliminate future errors to make this change.  The involved UF ID is 71805481.
>  
> Regards,
> Mike Blanchard
> System Analyst L3
> Information Services
> UF Health/Shands Healthcare

I believe we already handle their "Request 2".  If I am wrong and we _want_ to add this. We should do it under a separate issue.

As to Request 1, I would refine their request with these reasons:

1. No UF ID in results file.
1. UF ID not found in available Person Hub data.
1. UF ID found but names do not match

That said, would it be easier to manage three boolean columns? i.e.

1. ufid_in_results
1. ufid_in_person_hub
1. names_match

Not sure this will fly well with Patty's team, but their third reason "UF ID found but names do not match" is mixing two facts together. That feels like the road to hell. The permutations of fact mixing could easily get out of hand. The Epic team is now sending us DOB with the results and I expect we will add it to this data alignment work (Yes, I'll make an issue :-)). That's another test that might or might not pass. If we keep the test results in their own columns, blending them is simple logic for us and any downstream consumers.

**Comment by ljwoodley** [comment]
When the uf ids match but the names do not should we append the names from redcap results to `rejected_lab_data` so the person hub team can see where the differences occur? @pbchase

**Comment by ljwoodley** [comment]
Addressed by issue #95
