### ISSUE TITLE
Hyperlink in New Case Email is not actually a hyperlink

### ISSUE THREAD

**Issue by senrabc** [ctsit/tt_engine#78]
This is what it looks like in a mail client. I.E. Hyperlink is not clickable and due to the formatting of the paragraph it's hard to cut and paste too.

<img width="790" alt="Screen Shot 2020-06-17 at 10 32 09 AM" src="https://user-images.githubusercontent.com/874070/84911320-ff626980-b085-11ea-837c-95ca586ea44f.png">

**Comment by senrabc** [comment]
This is in Webmail - FYI.

**Comment by pbchase** [comment]
This is an email client issue.
