### ISSUE TITLE
Add this stuff to the readme

### ISSUE THREAD

**Issue by KevinHanson** [ctsit/tt_engine#8]
An SFTP server has been set up to allow input and output of screening and tracing data. The SSH public keys have been set up on sftp.ach.ufl.edu. To connect to this SFTP site use the following command:

sftp oneuftesting@sftp.ahc.ufl.edu

Here is a UF workflow diagram as of 5-15-20.
<img width="2049" alt="Screen Shot 2020-05-15 at 1 42 54 PM" src="https://user-images.githubusercontent.com/7871546/82087410-07fa0580-96be-11ea-93f2-5dd061d5599d.png">

**Comment by pbchase** [comment]
We're not going to do this one.
