### ISSUE TITLE
Write ETL to set sx_check_number in contacts

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#87]
Write an Rscript ETL job to set `sx_check_number` in the contacts project. Name the script `set_sx_check_number.R`. The script will need to once per day in the a.m. It must do these things:

1. Read dotenv data.
1. Identify the running instance
1. Set the script run date
1. Read the Contacts data
1. Filter for the `redcap_event_name == 'contact_tracing_arm_1'`
1. Filter for `contact_released_from_quarantine == 0 & is.na(contact_tracing_date)`
1. Mutate sx_check_number = round(days(today() - contact_tracing_date + 1))
1. Write sx_check_number back to Contacts.
1. Send an email report with a summary of the data read and the data written.
1. The email subject should be custom to this job, show the instance name and the script run time.
1. The email body should include:
- A tally of the rows read grouped by `contact_released_from_quarantine`
- A count of the rows written.

A good PR will include an addition to `examples/tt_engine_prod.cron` that runs `set_sx_check_number.R` at 0758, every day.

**Comment by ljwoodley** [comment]
> 6. Filter for contact_released_from_quarantine == 0 & is.na(contact_tracing_date)

> 7. Mutate sx_check_number = round(days(today() - contact_tracing_date + 1))

Point 6 says to filter for `is.na(contact_tracing_date)`. This makes the calculation in point 7 invalid as `contact_tracing_date` is always NA. 
@pbchase

**Comment by pbchase** [comment]
let's make that `!is.na(contact_tracing_date)`.  sorry.  my mistake

**Comment by ljwoodley** [comment]
Addressed by pr #89
