### ISSUE TITLE
Read "Birth Date" from lab results

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#92]
The Epic team has made a new "Birth Date" column available to us in the lab results. We should start reading it in `get_lab_result_data` so we can use it for record alignment in `align_lab_results_to_person_data` (That'll be in a different PR. Let's keep these small.) 

That said, I'm not sure we should write this new DOB into the result record. If we _require_ it to match to get align lab data with person hub data, it would just be noise. I can't imagine a scenario where we wouldn't require it to match. It's such a singular, immutable field it seem too important to not require. 

Thoughts? @tlstoffs, @ljwoodley, @ChemiKyle I welcome your thoughts here.

**Comment by ljwoodley** [comment]
I don't see any benefits to writing the dob into redcap results since there already is a dob field. We can use dob and uf id to match then get any secondary matches on name in `align_lab_results_to_person_data`

**Comment by ljwoodley** [comment]
Addressed by issue #98
