### ISSUE TITLE
Add an loaded_by_etl indicator to get_new_lab_results_for_cases so redcap rules can use it

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_engine#94]
`get_new_lab_results_for_cases` need to set some redcap field to indicate the source of the lab for every lab result it loads. 

This field should be added to the case project in the form _COVID-19 Case Symptoms and Labs_ (`covid19_case_longitudinal`). It should appear immediately after `case_lab_result`. The field should be hidden from the DIs at this time for the usual reasons. 

@tlstoffs, please design the field and note what you created here. please go ahead and add it to the conditions for sending the SMS alert.

@lawjames, once Taryn does that, please modify `get_new_lab_results_for_cases` to set the value of the field as needed to indicate our ETL loaded the data.

**Comment by pbchase** [comment]
@ljwoodley, I created the field in prod Cases. The name is `case_lab_loaded_by_etl`. it is a REDCap Yes/No field. It is on the lab form, please set it for each lab result you load in cases.

**Comment by ljwoodley** [comment]
Addressed by issue #96
